[package]
name = "balls_with_physics"
version = "0.3.0"
edition = "2021"
authors = ["Sandra"]
repository = "https://github.com/an-Iceberg/balls_with_physics"

[dependencies]
egui = "0.28.1"
egui-macroquad = "0.15.0"
macroquad = "0.3.26"
